---
- name: Common setup (SELinux + firewalld)
  hosts: all
  become: true
  roles:
    - common

- name: Frontend setup
  hosts: frontend
  become: true
  roles:
    - frontend

- name: Backend setup
  hosts: backend
  become: true
  roles:
    - backend
