- name: Bootstrap Python 3.8 on Amazon Linux
  hosts: frontend
  gather_facts: false
  become: true
  vars:
    ansible_python_interpreter: /bin/sh

  tasks:
    - name: Enable Python 3.8 using amazon-linux-extras
      shell: |
        amazon-linux-extras enable python3.8
        yum clean metadata
        yum install -y python3.8
      args:
        creates: /usr/bin/python3.8

    - name: Symlink python3 to python3.8
      file:
        src: /usr/bin/python3.8
        dest: /usr/bin/python3
        state: link

- name: Common setup (SELinux + firewalld)
  hosts: all
  become: true
  roles:
    - common

- name: Frontend setup
  hosts: frontend
  become: true
  roles:
    - frontend

- name: Backend setup
  hosts: backend
  become: true
  roles:
    - backend
