- name: Install Python 3.8 on Amazon Linux 2
  block:
    - name: Enable Python3.8 using amazon-linux-extras
      ansible.builtin.shell: |
        amazon-linux-extras enable python3.8
        yum install -y python3.8
      args:
        creates: /usr/bin/python3.8
      become: true

    - name: Create symlink for python3 to point to python3.8
      ansible.builtin.file:
        src: /usr/bin/python3.8
        dest: /usr/bin/python3
        state: link
      become: true
  when: ansible_distribution == "Amazon"


- name: Disable SELinux (Amazon Linux / RedHat)
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  when: ansible_os_family == "RedHat"
  become: true
- name: Stop firewalld (if present)
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: no
  ignore_errors: true
  become: true
- name: Install curl (on Debian-based systems)
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
  become: true
